
spring.application.name=Expense tracker
spring.config.import=secret.properties

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG

spring.flyway.enabled=false
spring.flyway.baselineOnMigrate = false

# Logging config
logging.config=classpath:logback-spring.xml


# including everything for testing
management.endpoints.web.exposure.include=*
## for prometheus(the last part)
# health,info,prometheus,metrics

## its for grafana
management.metrics.distribution.percentiles-histogram.http.server.requests=true


#############HIkary CP connection pool settings
spring.datasource.hikari.maximum-pool-size=5 
#this was set to 5 to test out the resilience, usually 10 is a good number

# How long a thread waits for a connection before throwing an exception
# 3 seconds - threads will fail quickly once pool is full, this is set for load testing
spring.datasource.hikari.connection-timeout=3000

# How long a connection can sit idle before being removed
## this means that inside hikaricp which has 10 connection to DB, if no api is getting called, and no connection is used for more than 10s,
# end it for now. will connect later
spring.datasource.hikari.idle-timeout=10000

# HikariCP will always keep at least this many connections open
spring.datasource.hikari.minimum-idle=1

# Optional - log pool stats every 30 seconds
spring.datasource.hikari.keepalive-time=30000

#It just warns ? it does not kill the connection.
#When the threshold is exceeded, HikariCP logs a warning with a stack trace
# showing where the connection was acquired. The connection itself stays open and continues running.
spring.datasource.hikari.leak-detection-threshold=5000