
spring.application.name=Expense tracker
spring.config.import=secret.properties

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG

spring.flyway.enabled=false
spring.flyway.baselineOnMigrate = false

## for prometheus(the last part)
management.endpoints.web.exposure.include=health,info,prometheus

## its for grafana
management.metrics.distribution.percentiles-histogram.http.server.requests=true

